
apiVersion: v1
kind: Service
metadata:
  name: zookeeper
  labels:
    app: zookeeper
    component: zookeeper
spec:
  ports:
  - port: 1234
    name: fake
  clusterIP: None
  selector:
    app: zookeeper
    component: zookeeper
