
apiVersion: v1
kind: ConfigMap
metadata:
  name: krb5-conf
data:
  krb5.conf: |
    [libdefaults]
     ignore_acceptor_hostname = true
     dns_canonicalize_hostname = false
     dns_lookup_realm = false
     ticket_lifetime = 24h
     forwardable = true
     rdns = false
     default_realm = EXAMPLE.COM

    [realms]
     EXAMPLE.COM = {
      kdc = krb5-0.krb5
      admin_server = krb5-0.krb5
     }

    [domain_realm]
     .example.com = EXAMPLE.COM
     example.com = EXAMPLE.COM
