
apiVersion: v1
kind: Secret
metadata:
  name: zookeeper-keytabs
data:
  zookeeper.keytab: BQIAAABWAAIAC0VYQU1QTEUuQ09NAAl6b29rZWVwZXIACXpvb2tlZXBlcgAAAAFfPUyVAgASACAFmcQiXlwhHHalflFcEpuhQZQoflbM+VwOBtm6x67VFwAAAAIAAABGAAIAC0VYQU1QTEUuQ09NAAl6b29rZWVwZXIACXpvb2tlZXBlcgAAAAFfPUyVAgARABA9xogXy8jya6j5HLlCojUVAAAAAg==
