
apiVersion: v1
kind: ConfigMap
metadata:
  name: zookeeper-jaas
data:
  jaas.conf: |-
    Server {
      com.sun.security.auth.module.Krb5LoginModule required
      useKeyTab=true
      keyTab="/etc/security/keytabs/zookeeper.keytab"
      storeKey=true
      useTicketCache=false
      principal="zookeeper/zookeeper";
    };

    Client {
      com.sun.security.auth.module.Krb5LoginModule required
      useKeyTab=true
      keyTab="/etc/security/keytabs/zookeeper.keytab"
      storeKey=true
      useTicketCache=false
      principal="zookeeper/zookeeper";
    };
